[package]
name = "wxrust-config"
version = "0.0.1-alpha2"
authors = [
    "Dmitry Pankratov <dmitry@pankratov.net>",
    "KENZ <KENZ.gelsoft@gmail.com>"
]
edition = "2021"
links = "wx-x86_64-pc-windows-msvc"

[features]
vendored = []
