[package]
name = "wx-x86_64-pc-windows-msvc"
version = "3.2.0"
authors = [
    "Dmitry Pankratov <dmitry@pankratov.net>",
    "KENZ <KENZ.gelsoft@gmail.com>"
]
edition = "2021"
links = "wx-x86_64-pc-windows-msvc"
